### ISSUE TITLE
Nothing is loading 

### ISSUE THREAD

**Issue by gaiamanthedog** [zalviandyr/MangaRa-Android#3]
Nothing loads

**Comment by zalviandyr** [comment]
The public API is down, so the app can't load the data.
You can try my similar app.
[Manga Nih](https://github.com/Manga-Nih/manga-nih-flutter)

**Comment by gaiamanthedog** [comment]
> The public API is down, so the app can't load the data.
> You can try my similar app.
> [Manga Nih](https://github.com/Manga-Nih/manga-nih-flutter)

It has great ui but it's not loading

**Comment by zalviandyr** [comment]
The app only accessible in Indonesia
